version: '3'

services:
  ros1_bridge:
    image: osrf/ros:foxy-ros1-bridge
    environment:
      - "ROS_HOSTNAME=bridge"
      - "ROS_MASTER_URI=http://ros1:11311"
    networks:
      - ros_network
    command: ros2 run ros1_bridge dynamic_bridge

  eufs_sim:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - ros_network
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - "/dev/dri:/dev/dri"
    privileged: true
    network_mode: host

networks:
  ros_network:
    driver: bridge
