version: '3'

services:
  ros1_bridge:
    build:
      context: .
      dockerfile: ros1_bridge.Dockerfile

    environment:
      - "ROS_HOSTNAME=localhost"
      - "ROS_MASTER_URI=http://localhost:11311"
    command: ros2 run ros1_bridge dynamic_bridge
    network_mode: host

  eufs_sim:
    build:
      context: .
      dockerfile: eufs_sim.Dockerfile

    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - "/dev/dri:/dev/dri"
    privileged: true
    network_mode: host

