// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: control.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_control_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_control_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3008000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3008000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_control_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_control_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_control_2eproto;
namespace TechnionFormulaAV {
namespace Messages {
class DriveInstructions;
class DriveInstructionsDefaultTypeInternal;
extern DriveInstructionsDefaultTypeInternal _DriveInstructions_default_instance_;
}  // namespace Messages
}  // namespace TechnionFormulaAV
PROTOBUF_NAMESPACE_OPEN
template<> ::TechnionFormulaAV::Messages::DriveInstructions* Arena::CreateMaybeMessage<::TechnionFormulaAV::Messages::DriveInstructions>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace TechnionFormulaAV {
namespace Messages {

// ===================================================================

class DriveInstructions :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:TechnionFormulaAV.Messages.DriveInstructions) */ {
 public:
  DriveInstructions();
  virtual ~DriveInstructions();

  DriveInstructions(const DriveInstructions& from);
  DriveInstructions(DriveInstructions&& from) noexcept
    : DriveInstructions() {
    *this = ::std::move(from);
  }

  inline DriveInstructions& operator=(const DriveInstructions& from) {
    CopyFrom(from);
    return *this;
  }
  inline DriveInstructions& operator=(DriveInstructions&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const DriveInstructions& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DriveInstructions* internal_default_instance() {
    return reinterpret_cast<const DriveInstructions*>(
               &_DriveInstructions_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(DriveInstructions* other);
  friend void swap(DriveInstructions& a, DriveInstructions& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DriveInstructions* New() const final {
    return CreateMaybeMessage<DriveInstructions>(nullptr);
  }

  DriveInstructions* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<DriveInstructions>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const DriveInstructions& from);
  void MergeFrom(const DriveInstructions& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DriveInstructions* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "TechnionFormulaAV.Messages.DriveInstructions";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_control_2eproto);
    return ::descriptor_table_control_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // float gas = 1;
  void clear_gas();
  static const int kGasFieldNumber = 1;
  float gas() const;
  void set_gas(float value);

  // float brakes = 2;
  void clear_brakes();
  static const int kBrakesFieldNumber = 2;
  float brakes() const;
  void set_brakes(float value);

  // float steering = 3;
  void clear_steering();
  static const int kSteeringFieldNumber = 3;
  float steering() const;
  void set_steering(float value);

  // float optimal_speed = 4;
  void clear_optimal_speed();
  static const int kOptimalSpeedFieldNumber = 4;
  float optimal_speed() const;
  void set_optimal_speed(float value);

  // @@protoc_insertion_point(class_scope:TechnionFormulaAV.Messages.DriveInstructions)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  float gas_;
  float brakes_;
  float steering_;
  float optimal_speed_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_control_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DriveInstructions

// float gas = 1;
inline void DriveInstructions::clear_gas() {
  gas_ = 0;
}
inline float DriveInstructions::gas() const {
  // @@protoc_insertion_point(field_get:TechnionFormulaAV.Messages.DriveInstructions.gas)
  return gas_;
}
inline void DriveInstructions::set_gas(float value) {
  
  gas_ = value;
  // @@protoc_insertion_point(field_set:TechnionFormulaAV.Messages.DriveInstructions.gas)
}

// float brakes = 2;
inline void DriveInstructions::clear_brakes() {
  brakes_ = 0;
}
inline float DriveInstructions::brakes() const {
  // @@protoc_insertion_point(field_get:TechnionFormulaAV.Messages.DriveInstructions.brakes)
  return brakes_;
}
inline void DriveInstructions::set_brakes(float value) {
  
  brakes_ = value;
  // @@protoc_insertion_point(field_set:TechnionFormulaAV.Messages.DriveInstructions.brakes)
}

// float steering = 3;
inline void DriveInstructions::clear_steering() {
  steering_ = 0;
}
inline float DriveInstructions::steering() const {
  // @@protoc_insertion_point(field_get:TechnionFormulaAV.Messages.DriveInstructions.steering)
  return steering_;
}
inline void DriveInstructions::set_steering(float value) {
  
  steering_ = value;
  // @@protoc_insertion_point(field_set:TechnionFormulaAV.Messages.DriveInstructions.steering)
}

// float optimal_speed = 4;
inline void DriveInstructions::clear_optimal_speed() {
  optimal_speed_ = 0;
}
inline float DriveInstructions::optimal_speed() const {
  // @@protoc_insertion_point(field_get:TechnionFormulaAV.Messages.DriveInstructions.optimal_speed)
  return optimal_speed_;
}
inline void DriveInstructions::set_optimal_speed(float value) {
  
  optimal_speed_ = value;
  // @@protoc_insertion_point(field_set:TechnionFormulaAV.Messages.DriveInstructions.optimal_speed)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Messages
}  // namespace TechnionFormulaAV

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_control_2eproto
