# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='common.proto',
  package='TechnionFormulaAV.Messages',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0c\x63ommon.proto\x12\x1aTechnionFormulaAV.Messages\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\"+\n\x08Vector3D\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\" \n\x08Vector2D\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\".\n\x0eTriggerMessage\x12\x10\n\x08type_url\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\r\"\xfd\x01\n\x06Header\x12\n\n\x02id\x18\x01 \x01(\r\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x34\n\x10steady_timestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x32\n\x06source\x18\x04 \x01(\x0e\x32\".TechnionFormulaAV.Messages.Module\x12<\n\x08triggers\x18\x05 \x03(\x0b\x32*.TechnionFormulaAV.Messages.TriggerMessage\x12\x10\n\x08priority\x18\x06 \x01(\x05\"a\n\x07Message\x12\x32\n\x06header\x18\x01 \x01(\x0b\x32\".TechnionFormulaAV.Messages.Header\x12\"\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any*\x84\x01\n\x06Module\x12\x12\n\x0eUNKNOWN_MODULE\x10\x00\x12\x12\n\x0e\x43ONTROL_MODULE\x10\x01\x12\x14\n\x10STATE_EST_MODULE\x10\x02\x12\x15\n\x11PERCEPTION_MODULE\x10\x03\x12\x19\n\x15REAL_TIME_DATA_MODULE\x10\x04\x12\n\n\x06SERVER\x10\x05*w\n\x07Mission\x12\x13\n\x0fMISSION_UNKNOWN\x10\x00\x12\x12\n\x0eMISSION_MANUAL\x10\x01\x12\x19\n\x15MISSION_STRAIGHT_LINE\x10\x02\x12\x11\n\rMISSION_EIGHT\x10\x03\x12\x15\n\x11MISSION_ENDURENCE\x10\x04\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])

_MODULE = _descriptor.EnumDescriptor(
  name='Module',
  full_name='TechnionFormulaAV.Messages.Module',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_MODULE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONTROL_MODULE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATE_EST_MODULE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PERCEPTION_MODULE', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REAL_TIME_DATA_MODULE', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SERVER', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=587,
  serialized_end=719,
)
_sym_db.RegisterEnumDescriptor(_MODULE)

Module = enum_type_wrapper.EnumTypeWrapper(_MODULE)
_MISSION = _descriptor.EnumDescriptor(
  name='Mission',
  full_name='TechnionFormulaAV.Messages.Mission',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MISSION_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MISSION_MANUAL', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MISSION_STRAIGHT_LINE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MISSION_EIGHT', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MISSION_ENDURENCE', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=721,
  serialized_end=840,
)
_sym_db.RegisterEnumDescriptor(_MISSION)

Mission = enum_type_wrapper.EnumTypeWrapper(_MISSION)
UNKNOWN_MODULE = 0
CONTROL_MODULE = 1
STATE_EST_MODULE = 2
PERCEPTION_MODULE = 3
REAL_TIME_DATA_MODULE = 4
SERVER = 5
MISSION_UNKNOWN = 0
MISSION_MANUAL = 1
MISSION_STRAIGHT_LINE = 2
MISSION_EIGHT = 3
MISSION_ENDURENCE = 4



_VECTOR3D = _descriptor.Descriptor(
  name='Vector3D',
  full_name='TechnionFormulaAV.Messages.Vector3D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='TechnionFormulaAV.Messages.Vector3D.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='TechnionFormulaAV.Messages.Vector3D.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='TechnionFormulaAV.Messages.Vector3D.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=147,
)


_VECTOR2D = _descriptor.Descriptor(
  name='Vector2D',
  full_name='TechnionFormulaAV.Messages.Vector2D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='TechnionFormulaAV.Messages.Vector2D.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='TechnionFormulaAV.Messages.Vector2D.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=181,
)


_TRIGGERMESSAGE = _descriptor.Descriptor(
  name='TriggerMessage',
  full_name='TechnionFormulaAV.Messages.TriggerMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type_url', full_name='TechnionFormulaAV.Messages.TriggerMessage.type_url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='TechnionFormulaAV.Messages.TriggerMessage.id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=229,
)


_HEADER = _descriptor.Descriptor(
  name='Header',
  full_name='TechnionFormulaAV.Messages.Header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='TechnionFormulaAV.Messages.Header.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='TechnionFormulaAV.Messages.Header.timestamp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='steady_timestamp', full_name='TechnionFormulaAV.Messages.Header.steady_timestamp', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source', full_name='TechnionFormulaAV.Messages.Header.source', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='triggers', full_name='TechnionFormulaAV.Messages.Header.triggers', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='priority', full_name='TechnionFormulaAV.Messages.Header.priority', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=485,
)


_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='TechnionFormulaAV.Messages.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='TechnionFormulaAV.Messages.Message.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='TechnionFormulaAV.Messages.Message.data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=487,
  serialized_end=584,
)

_HEADER.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_HEADER.fields_by_name['steady_timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_HEADER.fields_by_name['source'].enum_type = _MODULE
_HEADER.fields_by_name['triggers'].message_type = _TRIGGERMESSAGE
_MESSAGE.fields_by_name['header'].message_type = _HEADER
_MESSAGE.fields_by_name['data'].message_type = google_dot_protobuf_dot_any__pb2._ANY
DESCRIPTOR.message_types_by_name['Vector3D'] = _VECTOR3D
DESCRIPTOR.message_types_by_name['Vector2D'] = _VECTOR2D
DESCRIPTOR.message_types_by_name['TriggerMessage'] = _TRIGGERMESSAGE
DESCRIPTOR.message_types_by_name['Header'] = _HEADER
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.enum_types_by_name['Module'] = _MODULE
DESCRIPTOR.enum_types_by_name['Mission'] = _MISSION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Vector3D = _reflection.GeneratedProtocolMessageType('Vector3D', (_message.Message,), {
  'DESCRIPTOR' : _VECTOR3D,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:TechnionFormulaAV.Messages.Vector3D)
  })
_sym_db.RegisterMessage(Vector3D)

Vector2D = _reflection.GeneratedProtocolMessageType('Vector2D', (_message.Message,), {
  'DESCRIPTOR' : _VECTOR2D,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:TechnionFormulaAV.Messages.Vector2D)
  })
_sym_db.RegisterMessage(Vector2D)

TriggerMessage = _reflection.GeneratedProtocolMessageType('TriggerMessage', (_message.Message,), {
  'DESCRIPTOR' : _TRIGGERMESSAGE,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:TechnionFormulaAV.Messages.TriggerMessage)
  })
_sym_db.RegisterMessage(TriggerMessage)

Header = _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), {
  'DESCRIPTOR' : _HEADER,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:TechnionFormulaAV.Messages.Header)
  })
_sym_db.RegisterMessage(Header)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:TechnionFormulaAV.Messages.Message)
  })
_sym_db.RegisterMessage(Message)


# @@protoc_insertion_point(module_scope)
